import { IContentItem, Elements, IContentType } from '@kentico/kontent-delivery';
import { Session } from '../models/Session';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Thu, 09 Dec 2021 17:29:41 GMT'
 */
export type Agenda = IContentItem<{
  dateTimeToDateTime: Elements.DateTimeElement;
  journeyStage: Elements.TaxonomyElement;
  dateTimeFromDateTime: Elements.DateTimeElement;
  sessions: Elements.LinkedItemsElement<IContentItem>;
  name: Elements.TextElement;
  slug: Elements.UrlSlugElement;
}>;
