import { IContentItem, Elements } from '@kentico/kontent-delivery';
import { Room } from './Room';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Thu, 09 Dec 2021 17:29:41 GMT'
 */
export type Break = IContentItem<{
  room: Elements.LinkedItemsElement<Room>;
  duration: Elements.NumberElement;
  name: Elements.TextElement;
}>;
