import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Thu, 09 Dec 2021 17:29:41 GMT'
 */
export type Page = IContentItem<{
  subpages: Elements.LinkedItemsElement<IContentItem>;
  url: Elements.UrlSlugElement;
  showInNavigation: Elements.MultipleChoiceElement;
  title: Elements.TextElement;
  content: Elements.LinkedItemsElement<IContentItem>;
}>;
