import { IContentItem, Elements } from '@kentico/kontent-delivery';
import { Presentation } from './Presentation';
import { Room } from './Room';
import { Speaker } from './Speaker';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Thu, 09 Dec 2021 17:29:41 GMT'
 */
export type Session = IContentItem<{
  speaker: Elements.LinkedItemsElement<Speaker>;
  dateTimeToDateTime: Elements.DateTimeElement;
  dateTimeFromDateTime: Elements.DateTimeElement;
  name: Elements.TextElement;
  presentation: Elements.LinkedItemsElement<Presentation>;
  journeyStage: Elements.TaxonomyElement;
  location: Elements.LinkedItemsElement<Room>;
}>;
