import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Thu, 09 Dec 2021 17:29:42 GMT'
 */
export type SocialMediaPost = IContentItem<{
  type: Elements.MultipleChoiceElement;
  journeyStage: Elements.TaxonomyElement;
  topic: Elements.TaxonomyElement;
  title: Elements.TextElement;
  body: Elements.RichTextElement;
  media: Elements.LinkedItemsElement<IContentItem>;
}>;
