import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Thu, 09 Dec 2021 17:29:42 GMT'
 */
export type Venue = IContentItem<{
  rooms: Elements.LinkedItemsElement<IContentItem>;
  name: Elements.TextElement;
  journeyStage: Elements.TaxonomyElement;
  address: Elements.RichTextElement;
  media: Elements.LinkedItemsElement<IContentItem>;
  description: Elements.RichTextElement;
  nearbyLodging: Elements.LinkedItemsElement<IContentItem>;
  map: Elements.LinkedItemsElement<IContentItem>;
}>;
